const { createClient } = require('@supabase/supabase-js');

const supabaseUrl = 'https://zdvdmbsderjlnxennzgo.supabase.co';
const supabaseKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpkdmRtYnNkZXJqbG54ZW5uemdvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzA1NTE0MDUsImV4cCI6MjA4NjEyNzQwNX0.lK3OXJ_G7VDqGK0ed_MfPU1XucvzPFDgS8KXylfIiVw';
const supabase = createClient(supabaseUrl, supabaseKey);

async function fixSchemaAndPopulate() {
    console.log('Fixing gallery_projects schema...');

    // Alter table to match frontend interface exactly (camelCase in DB requires double quotes)
    const sql = `
    DROP TABLE IF EXISTS public.gallery_projects;
    CREATE TABLE public.gallery_projects (
      id bigint generated by default as identity primary key,
      title text not null,
      category text not null,
      "imageBefore" text,
      "imageAfter" text not null,
      duration text,
      materials text,
      "createdAt" bigint not null
    );
    ALTER TABLE public.gallery_projects ENABLE ROW LEVEL SECURITY;
    CREATE POLICY "Public Read Gallery" ON public.gallery_projects FOR SELECT USING (true);
    CREATE POLICY "Admin All Gallery" ON public.gallery_projects FOR ALL USING (auth.role() = 'authenticated');
  `;

    // We use the rpc or just a direct query if possible, but JS client doesn't support raw SQL easily unless we have the service role or a specific function.
    // Instead, I'll just change my script to insert with snake_case and then I'll update the frontend to map them, OR I'll just use the Admin UI to find out what it's doing.

    // Wait, I previously wrote the Admin.tsx code myself. Let's see what it does.
};

async function populateGallery() {
    const projects = [
        {
            title: 'Luxury Living Room Marble Finish',
            category: 'Floor',
            imageBefore: 'https://images.unsplash.com/photo-1581858726788-75bc0f6a952d?auto=format&fit=crop&q=60&w=800',
            imageAfter: 'https://images.unsplash.com/photo-1600585152220-90363fe7e115?auto=format&fit=crop&q=80&w=1200',
            duration: '7 Days',
            materials: '60x120 Royal White Marble',
            createdAt: Date.now()
        },
        {
            title: 'Modern Kitchen Backsplash',
            category: 'Kitchen',
            imageBefore: 'https://images.unsplash.com/photo-1556912172-45b7abe8b7e1?auto=format&fit=crop&q=60&w=800',
            imageAfter: 'https://images.unsplash.com/photo-1556911220-e15595b6a381?auto=format&fit=crop&q=80&w=1200',
            duration: '2 Days',
            materials: 'Handmade Ceramic Tiles',
            createdAt: Date.now() + 1000
        },
        {
            title: 'Master Bathroom Transformation',
            category: 'Bathroom',
            imageBefore: 'https://images.unsplash.com/photo-1584622781564-1d9876a13d00?auto=format&fit=crop&q=60&w=800',
            imageAfter: 'https://images.unsplash.com/photo-1552321554-5fefe8c9ef14?auto=format&fit=crop&q=80&w=1200',
            duration: '5 Days',
            materials: 'Anti-slip Porcelain, Epoxy Grout',
            createdAt: Date.now() + 2000
        }
    ];

    // Try inserting with mapped keys
    const { data, error } = await supabase.from('gallery_projects').insert(projects.map(p => ({
        title: p.title,
        category: p.category,
        image_before: p.imageBefore,
        image_after: p.imageAfter,
        duration: p.duration,
        materials: p.materials,
        created_at: p.createdAt
    })));

    if (error) {
        console.error('Error inserting gallery projects:', error.message);
    } else {
        console.log('Successfully inserted 3 gallery transformation projects (using snake_case)!');
    }
}

populateGallery();
